[package]
name = "caplog"
version = "0.1.0"
authors = ["alexa"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4"
log = { version = "0.4", features = ["std"] }

[dev-dependencies]
proptest = "0.10"
